### ISSUE TITLE
Site build error

### ISSUE THREAD

**Issue by Jotschi** [vert-x3/vertx-web-site#236]
I get the following build error if I try to build the master branch.

```
mvn clean site
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Vert.x Website 3.4.2
[INFO] ------------------------------------------------------------------------
Downloading: https://jitpack.io/com/github/mauricio/postgresql-async_2/12/db-async-common_2.12/0.2.21/db-async-common_2.12-0.2.21.pom
Downloading: https://jitpack.io/com/github/mauricio/postgresql-async_2/12/mysql-async_2.12/0.2.21/mysql-async_2.12-0.2.21.pom
Downloading: https://jitpack.io/com/github/mauricio/postgresql-async_2/12/postgresql-async_2.12/0.2.21/postgresql-async_2.12-0.2.21.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.559 s
[INFO] Finished at: 2017-08-14T22:59:03+02:00
[INFO] Final Memory: 32M/428M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project vertx-web-site: Could not resolve dependencies for project io.vertx:vertx-web-site:jar:3.4.2: Failed to collect dependencies at io.vertx:vertx-stackd to read artifact descriptor for com.github.mauricio.postgresql-async_2.12:db-async-common_2.12:jar:0.2.21: Could not transfer artifact com.github.mauricio.postgresql-async_2.12:db-async-co
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by Jotschi** [comment]
I worked around the issue by removing the vertx-stack-docs dependency.

**Comment by arai-wa** [comment]
I got same error.
Following lines are error log of `mvn clean site -X`

```
[ERROR] Failed to execute goal on project vertx-web-site: Could not resolve dependencies for project io.vertx:vertx-web-site:jar:3.7.0: Failed to collect dependencies at io.vertx:vertx-stack-docs:zip:docs:3.7.0 -> io.vertx:vertx-mysql-postgresql-client:zip:docs:3.7.0 -> com.github.mauricio:postgresql-async_2.12:jar:0.2.21 -> com.github.mauricio.postgresql-async_2.12:db-async-common_2.12:jar:0.2.21: Failed to read artifact descriptor for com.github.mauricio.postgresql-async_2.12:db-async-common_2.12:jar:0.2.21: Could not transfer artifact com.github.mauricio.postgresql-async_2.12:db-async-common_2.12:pom:0.2.21 from/to JitPack (https://jitpack.io): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project vertx-web-site: Could not resolve dependencies for project io.vertx:vertx-web-site:jar:3.7.0: Failed to collect dependencies at io.vertx:vertx-stack-docs:zip:docs:3.7.0 -> io.vertx:vertx-mysql-postgresql-client:zip:docs:3.7.0 -> com.github.mauricio:postgresql-async_2.12:jar:0.2.21 -> com.github.mauricio.postgresql-async_2.12:db-async-common_2.12:jar:0.2.21
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
        at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:246)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project io.vertx:vertx-web-site:jar:3.7.0: Failed to collect dependencies at io.vertx:vertx-stack-docs:zip:docs:3.7.0 -> io.vertx:vertx-mysql-postgresql-client:zip:docs:3.7.0 -> com.github.mauricio:postgresql-async_2.12:jar:0.2.21 -> com.github.mauricio.postgresql-async_2.12:db-async-common_2.12:jar:0.2.21
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:177)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
        ... 23 more
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at io.vertx:vertx-stack-docs:zip:docs:3.7.0 -> io.vertx:vertx-mysql-postgresql-client:zip:docs:3.7.0 -> com.github.mauricio:postgresql-async_2.12:jar:0.2.21 -> com.github.mauricio.postgresql-async_2.12:db-async-common_2.12:jar:0.2.21
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:300)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:325)
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:169)
        ... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for com.github.mauricio.postgresql-async_2.12:db-async-common_2.12:jar:0.2.21
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:283)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:199)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:544)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:528)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:418)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:372)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:360)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.doRecurse(DefaultDependencyCollector.java:513)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:467)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:372)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:360)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.doRecurse(DefaultDependencyCollector.java:513)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:467)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:372)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:360)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.doRecurse(DefaultDependencyCollector.java:513)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:467)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:372)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:360)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:263)
        ... 26 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact com.github.mauricio.postgresql-async_2.12:db-async-common_2.12:pom:0.2.21 from/to JitPack (https://jitpack.io): Not authorized , ReasonPhrase:Unauthorized.
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:453)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:255)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:232)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:268)
        ... 45 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact com.github.mauricio.postgresql-async_2.12:db-async-common_2.12:pom:0.2.21 from/to JitPack (https://jitpack.io): Not authorized , ReasonPhrase:Unauthorized.
        at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:52)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:364)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:76)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:590)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:258)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:529)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:430)
        ... 48 more
Caused by: org.apache.maven.wagon.authorization.AuthorizationException: Not authorized , ReasonPhrase:Unauthorized.
        at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1007)
        at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:962)
        at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:126)
        at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
        at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
        at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:569)
        at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:436)
        at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:413)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:456)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:359)
        ... 53 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by arai-wa** [comment]
This error occurs in the master branch.
But it didn't occur in the 3.4.0-release branch.
